version : "3"

services:
    database:
        image: mysql:5.6
        env_file:
             - env/.db_env
        ports:
            - "3306:3306"
    aeroform:
        image: skouriba/aeroform
        command: python manage.py runserver 0.0.0.0:8001
        env_file:
            - env/.aero_env
        deploy:
            replicas: 4
            restart_policy: 
                condition: on-failure
            resources: 
                limits:
                    cpus: '0.1'
                    memory: '512MB'
        ports:
            - "81:8001"

    visualizer:
        image: dockersamples/visualizer:stable
        ports:
          - "8080:8080"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                constraints: [node.role == manager]

