version : "3"

services:
    database:
        image: mysql:5.6
        volumes:
            - "~/mali_project/db:/var/lib/mysql"
        env_file:
             - env/.db_env
        ports:
            - "3306:3306"
    aeroform:
        image: skouriba/aeroform
        command: /bin/sh django_preparation_entrypoint.sh
        env_file:
            - env/.aero_env
        ports:
            - "81:8000"
        deploy:
            restart_policy:
                condition: on-failure
            replicas: 3
        depends_on:
            - "database"

    visualizer:
        image: dockersamples/visualizer:stable
        ports:
          - "8080:8080"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                constraints: [node.role == manager]

