version : "3"

services:
    database:
        image: mysql:5.6
        volumes:
            - "~/mali_project/db:/var/lib/mysql"
        env_file:
             - env/.db_env
        ports:
            - "3306:3306"
    aeroform:
        build: .
        command: python manage.py runserver 0.0.0.0:8001
        env_file:
            - env/.aero_env
        ports:
            - "81:8001"
        depends_on:
            - "database"

    visualizer:
        image: dockersamples/visualizer:stable
        ports:
          - "8080:8080"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                constraints: [node.role == manager]

