# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-07 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mali_project', '0005_auto_20190201_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='rdc_form_model',
            fields=[
                ('identifiant', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('venant_de', django_countries.fields.CountryField(max_length=2)),
                ('allant_a', django_countries.fields.CountryField(max_length=2)),
                ('adresse_etranger', models.CharField(blank=True, max_length=50)),
                ('numero_voyage', models.CharField(blank=True, max_length=7)),
                ('numero_siege', models.CharField(blank=True, max_length=50)),
                ('nom_famille', models.CharField(max_length=50)),
                ('numero_passport', models.CharField(max_length=50)),
                ('prenom', models.CharField(default=b'Neant', max_length=50)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(default=b'Neant', max_length=50)),
                ('genre', models.CharField(default=b'Homme', max_length=50)),
                ('telephone', models.CharField(default=b'Neant', max_length=13)),
                ('adresse_locale', models.CharField(default=b'Neant', max_length=50)),
                ('fievre', models.CharField(default=b'Oui', max_length=30)),
                ('cephale_douleur', models.BooleanField()),
                ('date_voyage', models.DateTimeField()),
                ('type_voyage', models.CharField(blank=True, max_length=20)),
                ('maux_de_tete', models.BooleanField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mali_project.Domain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
