# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-07 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdc_form_model',
            name='cephale_douleur',
            field=models.CharField(default=b'Non', max_length=13),
        ),
    ]
