# Generated by Django 2.0 on 2020-01-10 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdcmodel',
            name='domain',
        ),
    ]
