# Generated by Django 2.0 on 2020-01-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdc', '0002_remove_rdcmodel_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdcmodel',
            name='allant_a',
            field=models.CharField(max_length=50, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='rdcmodel',
            name='venant_de',
            field=models.CharField(max_length=50, verbose_name='Depart'),
        ),
    ]
