# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-09 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mali_project', '0005_auto_20190201_0348'),
        ('rdc', '0002_auto_20190207_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDCModel',
            fields=[
                ('identifiant', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('venant_de', django_countries.fields.CountryField(max_length=2)),
                ('allant_a', django_countries.fields.CountryField(max_length=2)),
                ('adresse_etranger', models.CharField(blank=True, max_length=50)),
                ('numero_voyage', models.CharField(blank=True, max_length=7)),
                ('numero_siege', models.CharField(blank=True, max_length=50)),
                ('nom_famille', models.CharField(max_length=50)),
                ('numero_passport', models.CharField(max_length=50)),
                ('prenom', models.CharField(default=b'Neant', max_length=50)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(default=b'Neant', max_length=50)),
                ('genre', models.CharField(default=b'Homme', max_length=50)),
                ('telephone', models.CharField(default=b'Neant', max_length=13)),
                ('adresse_locale', models.CharField(default=b'Neant', max_length=50)),
                ('fievre', models.CharField(default=b'Oui', max_length=30)),
                ('cephale_douleur', models.CharField(default=b'Non', max_length=13)),
                ('date_voyage', models.DateTimeField()),
                ('type_voyage', models.CharField(blank=True, max_length=20)),
                ('perte_appetit', models.CharField(blank=True, max_length=30)),
                ('fatigue_intense', models.CharField(blank=True, max_length=30)),
                ('douleur_musculaire', models.CharField(blank=True, max_length=30)),
                ('respiration_difficile', models.CharField(blank=True, max_length=30)),
                ('douleur_abdominale', models.CharField(blank=True, max_length=30)),
                ('difficulte_avaler', models.CharField(blank=True, max_length=30)),
                ('yeux_rouge', models.CharField(blank=True, max_length=30)),
                ('saignement_inexplique', models.CharField(blank=True, max_length=30)),
                ('deces_inexplique', models.CharField(blank=True, max_length=30)),
                ('temperature_arrive', models.FloatField()),
                ('temperature_depart', models.FloatField()),
                ('saignement_inexpliqe_agent', models.CharField(blank=True, max_length=30)),
                ('decision_officier', models.TextField(blank=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mali_project.Domain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='rdc_form_model',
            name='domain',
        ),
        migrations.DeleteModel(
            name='rdc_form_model',
        ),
    ]
