# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-16 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdc', '0003_auto_20190209_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdcmodel',
            name='numero_siege',
        ),
        migrations.AddField(
            model_name='rdcmodel',
            name='nom_compagnie',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rdcmodel',
            name='numero_emplacement',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rdcmodel',
            name='numero_matricule',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
