# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-22 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdc', '0005_auto_20190219_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdcmodel',
            name='allant_a',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rdcmodel',
            name='respiration_difficile',
            field=models.CharField(blank=True, max_length=30, verbose_name=b'Des difficult\xc3\xa9s respiratoires ?'),
        ),
        migrations.AlterField(
            model_name='rdcmodel',
            name='venant_de',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
