# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdc', '0007_auto_20190222_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdcmodel',
            name='cephale_douleur',
        ),
        migrations.RemoveField(
            model_name='rdcmodel',
            name='fievre',
        ),
        migrations.RemoveField(
            model_name='rdcmodel',
            name='lieu_naissance',
        ),
    ]
