# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-06 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdc', '0009_auto_20190222_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdcmodel',
            name='date_enregistrement',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rdcmodel',
            name='etat',
            field=models.CharField(default=b'Non approuv\xc3\xa9', max_length=15),
        ),
    ]
