# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-06 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdc', '0012_auto_20190306_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdcmodel',
            name='etat',
            field=models.CharField(max_length=15),
        ),
    ]
