# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-07 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdc', '0013_auto_20190306_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdcmodel',
            name='etat',
        ),
    ]
