# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import mali_project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mali_project', '0008_auto_20190314_0016'),
        ('rdc', '0016_auto_20190310_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDCModel',
            fields=[
                ('identifiant', models.CharField(default=mali_project.models.randomStringDigits, max_length=6, primary_key=True, serialize=False)),
                ('venant_de', django_countries.fields.CountryField(max_length=2)),
                ('allant_a', django_countries.fields.CountryField(max_length=2)),
                ('type_voyage', models.CharField(blank=True, max_length=20)),
                ('adresse_etranger', models.CharField(blank=True, max_length=50)),
                ('numero_vol', models.CharField(blank=True, max_length=7)),
                ('numero_siege', models.CharField(blank=True, max_length=50)),
                ('numero_cabine', models.CharField(blank=True, max_length=5)),
                ('nom_bateau', models.CharField(blank=True, max_length=30)),
                ('numero_matricule', models.CharField(blank=True, max_length=50)),
                ('nom_compagnie', models.CharField(blank=True, max_length=50)),
                ('nom_famille', models.CharField(max_length=50)),
                ('etat', models.CharField(choices=[('Invalide', 'Non valide'), ('Valide', 'Valide')], default=b'Invalide', max_length=30)),
                ('numero_passport', models.CharField(max_length=50)),
                ('prenom', models.CharField(default=b'Neant', max_length=50)),
                ('date_naissance', models.DateField()),
                ('genre', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default=b'Homme', max_length=10)),
                ('telephone', models.CharField(max_length=13)),
                ('adresse_locale', models.CharField(blank=True, max_length=50)),
                ('date_voyage', models.DateTimeField()),
                ('date_enregistrement', models.DateTimeField(auto_now=True)),
                ('perte_appetit', models.CharField(blank=True, max_length=30)),
                ('fatigue_intense', models.CharField(blank=True, max_length=30)),
                ('douleur_musculaire', models.CharField(blank=True, max_length=30)),
                ('respiration_difficile', models.CharField(blank=True, max_length=30, verbose_name=b'Des difficult\xc3\xa9s respiratoires ?')),
                ('douleur_abdominale', models.CharField(blank=True, max_length=30)),
                ('difficulte_avaler', models.CharField(blank=True, max_length=30)),
                ('yeux_rouge', models.CharField(blank=True, max_length=30)),
                ('saignement_inexplique', models.CharField(blank=True, max_length=30)),
                ('deces_inexplique', models.CharField(blank=True, max_length=30)),
                ('temperature_arrive', models.FloatField()),
                ('temperature_depart', models.FloatField()),
                ('saignement_inexpliqe_agent', models.CharField(blank=True, max_length=30)),
                ('decision_officier', models.TextField(blank=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mali_project.Domain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
