# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-18 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdc', '0019_auto_20190324_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rdcmodel',
            options={'verbose_name': 'Formulaire Congolais', 'verbose_name_plural': 'Formulaires Congolais'},
        ),
        migrations.AlterField(
            model_name='rdcmodel',
            name='date_enregistrement',
            field=models.DateField(auto_now=True, verbose_name="Date d'enregistrement"),
        ),
    ]
