# Generated by Django 2.0 on 2020-01-09 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mali_project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('objects', mali_project.models.DomainManager()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254)),
                ('contenu', models.TextField()),
            ],
        ),
    ]
