# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-12 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formModel',
            fields=[
                ('identifiant', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('date_vol', models.DateField()),
                ('numero_vol', models.CharField(max_length=7)),
                ('numero_siege', models.CharField(max_length=50)),
                ('venant_de', django_countries.fields.CountryField(max_length=2)),
                ('allant_a', django_countries.fields.CountryField(max_length=2)),
                ('numero_passport', models.CharField(max_length=50)),
                ('passport_emis_par', models.CharField(default=b'Police', max_length=50)),
                ('date_delivrance', models.DateField()),
                ('date_expiration', models.DateField()),
                ('num_visa', models.CharField(default=b'N/C', max_length=50)),
                ('visa_delivre_par', models.CharField(default=b'N/C', max_length=20)),
                ('nom_famille', models.CharField(max_length=50)),
                ('prenom', models.CharField(default=b'Neant', max_length=50)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(default=b'Neant', max_length=50)),
                ('genre', models.CharField(choices=[(b'Homme', b'Homme'), (b'Femme', b'Femme')], default=b'Homme', max_length=50)),
                ('nationalite', models.CharField(default=b'Neant', max_length=50)),
                ('profession', models.CharField(default=b'Neant', max_length=50)),
                ('telephone', models.CharField(default=b'Neant', max_length=13)),
                ('email', models.CharField(default=b'Neant', max_length=50)),
                ('adresse_locale', models.CharField(default=b'Neant', max_length=50)),
                ('adresse_etranger', models.CharField(default=b'Neant', max_length=50)),
                ('motif_voyage', models.CharField(max_length=100)),
                ('hebergement', models.CharField(max_length=100)),
                ('premiere_visite', models.CharField(choices=[(b'Oui', b'Oui'), (b'Non', b'Non')], default=b'Oui', max_length=50)),
                ('fievre', models.CharField(choices=[(b'Oui', b'Oui'), (b'Non', b'Non')], default=b'Oui', max_length=30)),
                ('diarrhee_vomissement', models.CharField(choices=[(b'Oui', b'Oui'), (b'Non', b'Non')], default=b'Oui', max_length=30)),
                ('cephale_douleur', models.CharField(choices=[(b'Oui', b'Oui'), (b'Non', b'Non')], default=b'Oui', max_length=30)),
                ('ecchymose', models.CharField(choices=[(b'Oui', b'Oui'), (b'Non', b'Non')], default=b'Oui', max_length=30)),
                ('contact_ebola', models.CharField(choices=[(b'Oui', b'Oui'), (b'Non', b'Non')], default=b'Oui', max_length=30)),
                ('etablissement_ebola', models.CharField(choices=[(b'Oui', b'Oui'), (b'Non', b'Non')], default=b'Oui', max_length=30)),
            ],
        ),
    ]
