# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-23 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mali_project', '0002_auto_20190118_2358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='formModel',
        ),
    ]
