# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-31 16:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mali_project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mali_project', '0003_delete_formmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('objects', mali_project.models.DomainManager()),
            ],
        ),
    ]
