# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-01 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mali_project', '0004_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='domain_name',
            new_name='name',
        ),
    ]
