# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-25 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mali_project', '0005_auto_20190201_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name=b'Nom')),
                ('email', models.EmailField(max_length=254)),
                ('contenu', models.TextField()),
            ],
        ),
    ]
