# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mali_project', '0007_auto_20190310_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='form_mali',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='form_rdc',
        ),
        migrations.DeleteModel(
            name='MaliModel',
        ),
        migrations.DeleteModel(
            name='RDCModel',
        ),
    ]
