# Generated by Django 2.0 on 2020-01-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mali', '0002_remove_malimodel_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='malimodel',
            name='diarrhee_vomissement',
            field=models.CharField(default='Non', max_length=30),
        ),
    ]
