# Generated by Django 2.0 on 2020-01-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mali', '0003_malimodel_diarrhee_vomissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malimodel',
            name='allant_a',
            field=models.CharField(max_length=50, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='venant_de',
            field=models.CharField(max_length=50, verbose_name='Depart'),
        ),
    ]
