# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mali', '0003_auto_20190216_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='malimodel',
            name='autre_element',
            field=models.CharField(default='Aucun', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='malimodel',
            name='saignement_nez',
            field=models.CharField(default=b'Non', max_length=30),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='contact_ebola',
            field=models.CharField(default=b'Non', max_length=30),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='ecchymose',
            field=models.CharField(default=b'Non', max_length=30),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='etablissement_ebola',
            field=models.CharField(default=b'Non', max_length=30),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='premiere_visite',
            field=models.CharField(default=b'Non', max_length=50),
        ),
    ]
