# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mali', '0004_auto_20190218_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malimodel',
            name='num_visa',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='passport_emis_par',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='visa_delivre_par',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
