# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-19 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mali', '0005_auto_20190218_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='malimodel',
            old_name='numero_emplacement',
            new_name='numero_siege',
        ),
        migrations.RenameField(
            model_name='malimodel',
            old_name='numero_voyage',
            new_name='numero_vol',
        ),
        migrations.AddField(
            model_name='malimodel',
            name='nom_bateau',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='malimodel',
            name='numero_cabine',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='malimodel',
            name='type_voyage',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
