# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-22 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mali', '0006_auto_20190219_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malimodel',
            name='allant_a',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='venant_de',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
