# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-22 12:18
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mali', '0007_auto_20190222_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malimodel',
            name='allant_a',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='venant_de',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
