# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import mali_project.models


class Migration(migrations.Migration):

    dependencies = [
        ('mali', '0008_auto_20190222_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malimodel',
            name='identifiant',
            field=models.CharField(default=mali_project.models.randomStringDigits, max_length=6, primary_key=True, serialize=False),
        ),
    ]
