# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-24 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mali', '0009_auto_20190222_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malimodel',
            name='autre_element',
            field=models.CharField(max_length=55),
        ),
    ]
