# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-25 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mali', '0010_auto_20190224_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malimodel',
            name='motif_voyage',
            field=models.CharField(max_length=100, verbose_name=b'Quel est le motif de votre voyage ?'),
        ),
    ]
