# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-06 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mali', '0012_auto_20190306_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malimodel',
            name='etat',
            field=models.CharField(max_length=15),
        ),
    ]
