# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-07 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mali', '0016_remove_malimodel_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='malimodel',
            name='etat',
            field=models.CharField(default='Non valide', max_length=30),
            preserve_default=False,
        ),
    ]
