# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-23 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mali', '0019_malimodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malimodel',
            name='adresse_etranger',
            field=models.CharField(blank=True, max_length=50, verbose_name="Adresse a l'etranger"),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='adresse_locale',
            field=models.CharField(blank=True, max_length=50, verbose_name='Adresse locale'),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='allant_a',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='date_enregistrement',
            field=models.DateField(auto_now=True, verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='date_naissance',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='date_voyage',
            field=models.DateTimeField(verbose_name='Date du voyage'),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='etat',
            field=models.CharField(choices=[('Invalide', 'Non valide'), ('Valide', 'Valide')], default=b'Invalide', max_length=30, verbose_name='Etat'),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='nom_bateau',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nom du bateau'),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='nom_compagnie',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nom de la compagnie'),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='nom_famille',
            field=models.CharField(max_length=50, verbose_name='Nom de famille'),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='numero_cabine',
            field=models.CharField(blank=True, max_length=5, verbose_name='Numero de la cabine'),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='numero_matricule',
            field=models.CharField(blank=True, max_length=50, verbose_name='Immatriculation du vehicule'),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='numero_passport',
            field=models.CharField(max_length=50, verbose_name='Numero de passport'),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='numero_siege',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numero du siege'),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='numero_vol',
            field=models.CharField(blank=True, max_length=7, verbose_name='Numero du vol'),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='venant_de',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Depart'),
        ),
    ]
