# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mali', '0020_auto_20190323_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malimodel',
            name='date_enregistrement',
            field=models.DateField(verbose_name="Date d'enregistrement"),
        ),
    ]
