# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-18 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mali', '0021_auto_20190324_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='malimodel',
            options={'verbose_name': 'Formulaire Malien', 'verbose_name_plural': 'Formulaires Maliens'},
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='date_delivrance',
            field=models.DateField(verbose_name='Date de delivrance'),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='date_enregistrement',
            field=models.DateField(auto_now=True, verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='date_expiration',
            field=models.DateField(verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='num_visa',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numero du VISA'),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='passport_emis_par',
            field=models.CharField(blank=True, max_length=50, verbose_name="Lieu d'etablissement"),
        ),
        migrations.AlterField(
            model_name='malimodel',
            name='visa_delivre_par',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ou avez-vous obtenu votre Visa ?'),
        ),
    ]
